// Mock data for the ProcureX application

const mockData = {
    // Workspace roles are assigned after onboarding, not during initial authentication.
    roles: ['buyer', 'supplier', 'admin'],
    accountTypes: ['new user', 'existing user', 'admin'],
    currentRole: null,
    registrationDraft: {
        email: '',
        phone: ''
    },
    pendingAccount: null,
    session: {
        isAuthenticated: false,
        isNewUser: true,
        email: null
    },
    eKycProfile: {
        status: 'not_started',
        role: null
    },
    eKycRegistryRecord: null,
    mockAuth: {
        signupExample: {
            email: 'newuser@procurex.test',
            phone: '+255 712 345 678',
            password: 'Newuser1!'
        },
        accounts: [
            {
                email: 'newuser@procurex.test',
                phone: '+255 712 345 678',
                password: 'Newuser1!',
                role: null,
                accountType: 'new user',
                isNewUser: true,
                ekycCompleted: false,
                displayName: 'New User Account'
            },
            {
                email: 'johndoe@procurex.test',
                phone: '+255 713 111 222',
                password: 'Procure1!',
                role: null,
                accountType: 'existing user',
                isNewUser: false,
                ekycCompleted: true,
                displayName: 'John Doe'
            },
            {
                email: 'admin@procurex.test',
                phone: '+255 715 555 666',
                password: 'Admin123!',
                role: 'admin',
                accountType: 'admin',
                isNewUser: false,
                ekycCompleted: true,
                displayName: 'Admin User'
            }
        ]
    },

    // User data
    users: {
        buyer: {
            name: 'John Doe',
            organization: 'Ministry of Health',
            trustTier: 'Gold',
            riskScore: 85,
            bidLimit: 5000000
        },
        supplier: {
            name: 'ABC Construction Ltd',
            organization: 'ABC Construction Ltd',
            trustTier: 'Silver',
            riskScore: 78,
            bidLimit: 2000000
        },
        admin: {
            name: 'Admin User',
            organization: 'ProcureX Platform',
            permissions: ['all']
        }
    },

    // Dashboard KPIs
    kpis: {
        admin: {
            activeUsers: 1247,
            pendingVerifications: 23,
            supportTickets: 8,
            systemUptime: 99.8
        },
        buyer: {
            activeTenders: 12,
            draftTenders: 5,
            approvalsNeeded: 3,
            totalSpend: 25000000
        },
        supplier: {
            matchedTenders: 8,
            bidsInProgress: 3,
            closing48h: 2,
            watchlist: 15
        }
    },

    // Tenders data
    tenders: [
        {
            id: 'T001',
            title: 'Construction of Rural Health Centers',
            type: 'Works',
            status: 'Open',
            budget: 5000000000,
            closingDate: '2026-06-12',
            organization: 'Ministry of Health',
            description: 'Construction of 5 rural health centers in Dodoma region',
            eligibility: 'Registered contractors with Class G1 license',
            documents: ['BOQ.pdf', 'Drawings.pdf', 'Specifications.pdf']
        },
        {
            id: 'T002',
            title: 'Supply of Medical Equipment',
            type: 'Goods',
            status: 'Evaluation',
            budget: 1200000000,
            closingDate: '2026-04-30',
            organization: 'Muhimbili Hospital',
            description: 'Supply and installation of medical imaging equipment',
            eligibility: 'Licensed medical equipment suppliers',
            documents: ['Specs.pdf', 'Requirements.pdf']
        },
        {
            id: 'T003',
            title: 'IT Infrastructure Upgrade',
            type: 'Service',
            status: 'Awarded',
            budget: 800000000,
            closingDate: '2026-04-18',
            organization: 'Tanzania Revenue Authority',
            description: 'Network infrastructure and cybersecurity upgrade',
            eligibility: 'Certified IT service providers',
            documents: ['TOR.pdf', 'Network_Diagram.pdf']
        }
    ],

    // Procurement setup used by the create tender wizard.
    procurementSetup: {
        methods: ['Open Tender', 'Invited Tender'],
        types: [
            {
                id: 'goods',
                label: 'Goods',
                description: 'Physical items, equipment, stock, and supplies.',
                categories: [
                    'Telecommunication Equipment',
                    'Motor Vehicles',
                    'Water Meters and Spare Parts',
                    'Water Pumps and Spare Parts',
                    'Water Filters',
                    'Water Trucks',
                    'Water and Sewer Treatment Equipment and consumables',
                    'Water Survey Equipment',
                    'Water Well Drilling Equipment',
                    'Animal Feeds',
                    'Animals(Livestock) and Related Products',
                    'Animal Watering Machines',
                    'Veterinary Equipment and Supplies',
                    'Wagons and Coaches',
                    'Wagons and Coaches Spare parts',
                    'Locomotive Engines',
                    'Motor Trolleys',
                    'Rail, Sleepers and Clips',
                    'Railway Machinery',
                    'Railway Cranes',
                    'Rail on Truck Equipment (Tamping machinery, Truck Recording Cars, Railway Relaying Machines)',
                    'Furnaces and Incinerators Equipment',
                    'Mining and Quarrying Equipment',
                    'Abrasives and Smoothing Materials',
                    'Nuclear and Radioactive Products',
                    'Packaging Materials',
                    'Marine Vessels',
                    'Aircraft',
                    'Metal, Aluminium and Glass',
                    'Elevators and Escalators',
                    'Fire Fighting Equipment',
                    'Funeral Supplies',
                    'Land Survey Equipment',
                    'Land Cleaning Equipment',
                    'Land Leveling Equipment',
                    'Accommodation and Office furniture and accessories',
                    'Aerospace systems and components and equipment',
                    'Agents affecting water and electrolytes',
                    'Agricultural and forestry and landscape machinery and equipment',
                    'Anti infective drugs',
                    'Antineoplastic agents drugs/Anticancer drugs',
                    'Arts and crafts equipment and accessories and supplies',
                    'Audio and visual presentation and composing equipment',
                    'Autonomic nervous system drugs',
                    'Bank Notes Canceller/Punching Machines',
                    'Batteries and generators and kinetic power transmission',
                    'Bedclothes and table and kitchen linen and towels',
                    'Beehives and Accessories',
                    'Beverages',
                    'Bread and bakery products',
                    'Camping and outdoor equipment and accessories',
                    'Cardiac supplies and Accessories',
                    'Cardiovascular drugs',
                    'Central nervous system drugs',
                    'Cereal and pulse products',
                    'Chicken processing machinery and equipment',
                    'Chocolate and sugars and sweeteners and confectionary products',
                    'Classroom and instructional furniture and accessories',
                    'Classroom decoratives and supplies',
                    'Cleaning Equipment and Supplies',
                    'Clinical nutrition',
                    'Clothing and Uniforms',
                    'Collectibles and awards',
                    'Commercial and industrial furniture and accessories',
                    'Communications Devices and Accessories',
                    'Components for information technology or broadcasting or telecommunications',
                    'Computer Equipment and Accessories',
                    'Computer Software',
                    'Concrete and cement and plaster',
                    'Concrete poles',
                    'Construction and maintenance support equipment',
                    'Consumer electronics',
                    'Containers and storage',
                    'Dairy products',
                    'Data Voice or Multimedia Network Equipment or Platforms and Accessories',
                    'Dental equipment and supplies',
                    'Developmental and professional teaching aids and materials and accessories and supplies',
                    'Dialysis equipment and supplies',
                    'Domestic Gas',
                    'Domestic appliances',
                    'Domestic kitchenware and kitchen supplies',
                    'Domestic wall treatments',
                    'Doors and windows and glass',
                    'Drugs affecting the ears, eye, nose and skin',
                    'Drugs affecting the gastrointestinal system',
                    'Drugs affecting the respiratory tract',
                    'Earth and stone (Mchanga, Vifusi na Kokoto)',
                    'Edible oils and fats',
                    'Electrical Testing Equipment',
                    'Electrical equipment and components and supplies',
                    'Electrical wire and cable and harness',
                    'Electronic hardware and component parts and accessories',
                    'Electronic manufacturing machinery and equipment and accessories',
                    'Electronic reference material',
                    'Emergency and field medical services products',
                    'Exterior finishing materials',
                    'Fertilizers, Plants Nutrients and herbicides',
                    'Fishing and aquaculture equipment',
                    'Fishing and hunting equipment',
                    'Fitness equipment',
                    'Floor coverings',
                    'Footwear',
                    'Foundry machines and equipment and supplies',
                    'Fruits (Fresh, Organic, Dried, Frozen, Pured, Canned or Jarred)',
                    'Fuels',
                    'Gymnastics and boxing equipment',
                    'Heavy construction machinery and equipment',
                    'Hematolic drugs',
                    'Hormones and hormone antagonists',
                    'Hospital beds and Furnitures',
                    'Immunomodulating drugs',
                    'Independent living aids for the physically challenged',
                    'Industrial food and beverage equipment',
                    'Industrial machine tools',
                    'Industrial process machinery and equipment and supplies',
                    'Industrial refrigeration',
                    'Building Insulation Materials',
                    'Interior finishing materials',
                    'Intravenous and arterial administration products',
                    'Laboratory and scientific equipment',
                    'Laboratory supplies and fixtures',
                    'Lapidary machinery and equipment',
                    'Leatherworking repairing machinery and equipment',
                    'Lighting Fixtures and Accessories',
                    'Lubricants',
                    'Luggage and handbags and packs and cases',
                    'Mass transfer equipment',
                    'Material handling machinery and equipment',
                    'Meat and Poultry Products',
                    'Medical apparel and textiles',
                    'Radiology products',
                    'Medical facility products',
                    'Medical sterilization products',
                    'Medical training and education supplies',
                    'Merchandising furniture and accessories',
                    'Metal cutting machinery and accessories',
                    'Metal forming machinery and accessories',
                    'Metal treatment machinery',
                    'Minerals and ores and metals',
                    'Miscellaneous drug categories',
                    'Mixers and their parts and accessories',
                    'Motor Vehicle Components and Accessories',
                    'Motor vehicle Diagnostic Machines and Working Tools',
                    'Musical Instruments and parts and accessories',
                    'Newspaper',
                    'Non motorized cycles',
                    'Nuts and seeds',
                    'Office Supplies and accessories',
                    'Office machines their supplies and accessories',
                    'Oil and gas drilling and exploration equipment',
                    'Oil and gas drilling and operation materials',
                    'Oil and gas operating and production equipment',
                    'Orthopedic and prosthetic and sports medicine products',
                    'Orthopedic surgical implants',
                    'Packing supplies',
                    'Patient care and treatment products and supplies',
                    'Patient exam and monitoring products',
                    'Permanent structures',
                    'Personal care products',
                    'Safety and security equipment',
                    'Pest control products',
                    'Petroleum processing machinery',
                    'Photographic or filming or video equipment and supplies',
                    'Physical and occupational therapy and rehabilitation products',
                    'Plumbing fixtures',
                    'Portable Structure Building Components',
                    'Portable Structures',
                    'Postmortem and mortuary equipment and supplies',
                    'Power plants and equipment',
                    'Prefabricated structures',
                    'Prepared and preserved foods',
                    'Printed Books, Textbooks and Reading Materials',
                    'Printing and publishing machinery/equipment and accessories',
                    'Railway and tramway machinery and equipment',
                    'Rapid prototyping machinery and accessories',
                    'Raw materials processing machinery',
                    'Recreation and playground and swimming and spa equipment and supplies',
                    'Respiratory and anesthesia and resuscitation products',
                    'Road Testing Kits',
                    'Roads and landscape architecture and construction materials',
                    'Sawmilling and lumber processing machinery and equipment',
                    'Seafood',
                    'Seasonings and preservatives',
                    'Security and surveillance Equipment',
                    'Seeds and Seedlings',
                    'Sewing supplies and accessories',
                    'Spacecraft',
                    'Specimen collection and storage supplies',
                    'Sports equipment and accessories',
                    'Stationery',
                    'Structural building products (Blocks, Bricks, Tiles and Flagstones)',
                    'Structural components and basic shapes',
                    'Structural Metals, Bars and Sheets',
                    'Suptum screening drugs',
                    'Surgical products',
                    'Fabrics and Leather Materials',
                    'Textile and fabric machinery and accessories',
                    'Timber',
                    'Timepieces, Jewellery and Gemstones',
                    'Tobacco and smoking products and substitutes',
                    'Toys and games',
                    'Transportation components and systems',
                    'Transportation services equipment',
                    'Underground mining structures and materials',
                    'Urine Screening Drugs',
                    'Vegetables (Fresh, Organic, Dried, Frozen, Canned or Jarred)',
                    'Vehicle bodies and trailers',
                    'Veterinary nutritional supplement',
                    'Waste collection bags',
                    'Water Pipes and Fittings',
                    'Water Supply Equipment',
                    'Water Treatment Chemicals',
                    'Water Treatment Equipment',
                    'Welding and soldering and brazing machinery and accessories and supplies',
                    'Well drilling and operation equipment',
                    'Window treatments',
                    'Wire machinery and equipment',
                    'Wood Briquette',
                    'Wooden poles',
                    'Wound care products',
                    'Measuring , observing and testing instruments',
                    'Heating, ventilation, air circulation and condition Equipment and Accessories',
                    'Veterinary Pharmaceutical and Vaccines',
                    'Painting Products',
                    'Banknotes and Coins Processing',
                    'Signage and accessories',
                    'Motorized cycles',
                    'Marine Vessels Equipment, Spareparts and Accessories',
                    'Pharmaceuticals',
                    'Laboratory equipment and reagents',
                    'Medical Supplies and Equipment',
                    'Vision correction or cosmetic eyewear (eye glasses/spectacles) and related products',
                    'Floriculture and silviculture products',
                    'Mattresses and Sleep Sets',
                    'Aviation Fuel',
                    'Forensic equipment, supplies and accessories',
                    'Live fish',
                    'Live insects',
                    'Decoration Equipment and Accessories',
                    'Natural Gas Distribution Accessories and Equipment/Machineries',
                    'Firearms, Ammunitions and Accessories',
                    'Heavy Duty Gas Cooking Stoves (for Mass Cooking)',
                    'Sisal and sisal fibers',
                    'Fuel Additives',
                    'Coal',
                    'Fuel pumps and spare parts'
                ]
            },
            {
                id: 'works',
                label: 'Works',
                description: 'Construction, rehabilitation, infrastructure, and civil works.',
                categories: [
                    'Building Contractors',
                    'Civil Contractors',
                    'Mechanical Contractors',
                    'Electrical Contractors',
                    'Specialist Building - Carpentry and Joinery',
                    'Specialist Building - Concreting Works',
                    'Specialist Building - Interior Decoration',
                    'Specialist Building - Concrete Treatment and Repairs',
                    'Specialist Building - Water Proofing Installations',
                    'Specialist Building - Paving',
                    'Specialist Building - Pre Fabricated Buildings',
                    'Specialist Building - Demolition',
                    'Specialist Building - Conservation of Old Building',
                    'Specialist Civil - Pilling',
                    'Specialist Civil - Drilling Works',
                    'Specialist Civil - Labour Based Road Works',
                    'Specialist Civil - Land Scaping and Slope Protections',
                    'Specialist Civil - Treatments Plants and Water Works',
                    'Specialist Civil - Marine Works',
                    'Specialist Civil - Tunneling and Underpinning',
                    'Specialist Civil - Tunneling and Mining Works',
                    'Specialist Electrical - Telecommunications ICT and Security Systems Installations',
                    'Specialist Electrical - Power Generation Equipment Installations and Maintenance',
                    'Specialist Electrical - Electric Power lines and Systems',
                    'Specialist Electrical - Air Conditioning and Refrigeration',
                    'Specialist Mechanical - Heating Ventilation and Air Conditioning',
                    'Specialist Mechanical - Fabrication and Installation of Tanks',
                    'Specialist Mechanical - Repair and Installation of Motor Vehicle',
                    'Specialist Mechanical - Scaffolding and Formwork',
                    'Specialist Mechanical - Marine Vessels - Fabrication and Maintenance',
                    'Specialist Mechanical - Pre Fabrication and Erection of Steel Structures',
                    'Specialist Mechanical - Elevators and Escalators Installation and Maintenance',
                    'Specialist Mechanical - Plumbing and Sanitations',
                    'Specialist Mechanical - Metal, Aluminium and Glass Works',
                    'Specialist Mechanical - Fabrication, Installation and Maintenance of Oil and Gas Infrastructure',
                    'Specialist Civil - Road Marking and Furniture',
                    'Specialist Electrical - Renewable Energy Installation - Solar',
                    'Specialist Mechanical - Air Conditioning and Refrigeration',
                    'Specialist Mechanical - Fire Prevention and Protections',
                    'Specialist Mechanical - Installations and Maintenance of Industrial Plant',
                    'Specialist Mechanical - Marine Structure, Ferries and Boat Building',
                    'Specialist Mechanical- installation of biomedical equipment',
                    'Specialist-Maintenance and Repair of Hospital Equipment'
                ]
            },
            {
                id: 'services',
                label: 'Service',
                description: 'Operational services where advisory expertise is not the main component.',
                categories: [
                    'Auction Services',
                    'Printing Services (Business Stationery, Books, Booklets, Brochures, Leaflets, Cards, Forms, Labels, Manuals and Maps)',
                    'Desktop publishing services',
                    'Digital Printing Services',
                    'Engraving Services',
                    'Mailing Services',
                    'Warehousing and Storage Services',
                    'Catering Services',
                    'Building and Compound Cleaning Services',
                    'Fumigation Services',
                    'Security Services',
                    'Service and Maintenance of ICT Equipment',
                    'Service and Maintenance of Fire Fighting Equipment',
                    'Agricultural products Grinding and Milling Services',
                    'Service and Maintenance of Fire Security System',
                    'Internet Services',
                    'Insurance and Brokerage Services',
                    'Conference and Related Services',
                    'Repair and Maintenance of Air conditioners',
                    'Repair and Maintenance of Gymnastic equipment',
                    'Repair and Maintenance of Electrical equipment',
                    'Repair and Maintenance of Jet Machines',
                    'Repair and Maintenance of Backhoe and Excavator Machines',
                    'Repair and Maintenance of Water Pumps and Water Tanks',
                    'Repair and Maintenance of Gas Export Compressors',
                    'Repair and Maintenance of Mining and Quarrying Equipment',
                    'Repair and Maintenance of Power generation plants and equipment',
                    'Advertising Services',
                    'Real Estate Management Services',
                    'Car hiring services',
                    'Documentary and documentation Services',
                    'Events management',
                    'Graphics design services',
                    'Hiring of Printing and Photocopying Services',
                    'Hiring of equipment and plants',
                    'Hospitality services',
                    'Hotel Reservation Services',
                    'Labour services (Repair and Construction Activities)',
                    'Laundry services',
                    'Material packing and handling services',
                    'Packaging Services',
                    'Repair and Maintenance of Furniture and Fittings',
                    'Repair and Maintenance of Locomotives',
                    'Repair and Maintenance of Motor Vehicles (vehicles and motor cycle)',
                    'Repair and Maintenance of Plumbing systems',
                    'Repair and Maintenance of aircrafts and aviation equipment',
                    'Repair and Maintenance of marine equipment',
                    'Repair and Maintenance of other Office Equipment,',
                    'Service and Maintenance of Elevators, escalators and conveyors',
                    'Tailoring services',
                    'Transportation and Handling Services',
                    'Travel facilitation (Ticketing, Visa, Tours, Hotel bookings)',
                    'Veterinary services',
                    'Clearing and Forwarding Services',
                    'Finance and Banking Services',
                    'Network Services',
                    'Voice and Data Services',
                    'Revenue Collection Agency Services',
                    'Video Production Services',
                    'Audio Production Services',
                    'Radio Broadcasting Services',
                    'Television Broadcasting Services',
                    'Online Media Broadcasting Services',
                    'Agricultural seeds treatment, preservation and processing',
                    'Calibration Services',
                    'Machining Services',
                    'ICT System Maintenance and Support',
                    'Water and Sewer treatment Services',
                    'Non Hazardous Waste Management Services',
                    'Hazardous Waste Management Services',
                    'Metal smelting and refining and forming processes',
                    'Metal finishing services',
                    'Repair and maintenance of Medical Equipment',
                    'Material and/ or  product testing and inspection services',
                    'Geological samples testing services',
                    'Vehicle Tracking and Fleet Management Services',
                    'Labour services (General human resources provision)',
                    'Ground Handling Services for Air Transport',
                    'Operation of Government Recreational Buildings or Facilities (Clubs, stadiums, events venues)',
                    'Operation of Government Food Services Buildings or Facilities (Canteens, Cafeteria)',
                    'Operation of Government Commercial Buildings (Shops, Malls, Marketplaces)',
                    'Operation of Government Accommodation Buildings (Housing Complex, Dormitories or Residential Facilities)',
                    'Operation of Government Office Buildings',
                    'Operation of Government Transportation Buildings or Facilities (Terminals, Parking)',
                    'Operation of Government Power/Energy Buildings or Facilities (Plants, Substations)',
                    'Operation of Government Communication Buildings or Facilities (Broadcasting Towers/Facilities)',
                    'Venues Decoration Services',
                    'Passenger transportation services',
                    'Material treatment Services',
                    'Motor vehicles conversion or modification services',
                    'Forest products harvesting and processing',
                    'Forestry Services',
                    'Land Regularization Services',
                    'Miscellaneous Port Services',
                    'Passenger Air Transportation Services',
                    'Cargo Air Transportation Services',
                    'Aerobics and fitness services',
                    'Vehicle cleaning services',
                    'Crop Cultivation Services',
                    'Flight Data Monitoring Services',
                    'Management and Operation of Airline and Aviation Systems',
                    'Motorcycle hiring services',
                    'Repair and Maintenance of Security and Surveillance Equipment',
                    'Repair and Maintenance of Laboratory Equipment',
                    'Wildlife conservation and protection services',
                    'Wildlife control and monitoring services',
                    'Wildlife products harvesting and processing/taxidermy',
                    'Manual Water Meter Reading Services and Related Services',
                    'Underwater Diving Services',
                    'Medical Laboratory Services'
                ]
            },
            {
                id: 'consultancy',
                label: 'Consultancy',
                description: 'Professional advisory, research, design, audit, and expert assignments.',
                categories: [
                    'Information Technology Consultancy',
                    'Business Process Consultancy',
                    'Software Development',
                    'Systems Operations',
                    'Systems Supports and Administration',
                    'Management Consultancy',
                    'Human Resources Consultancy',
                    'Educational Consultancy',
                    'Legal Services Consultancy',
                    'Environmental Consultancy',
                    'Energy Consultancy',
                    'Health Care Consultancy',
                    'Public Relations Consultancy',
                    'Marketing Consultancy',
                    'Organisation and Change Management Consultancy',
                    'Procurement Consultancy',
                    'Tax Consultancy',
                    'Accountancy and auditing',
                    'Financial and audit Services Consultancy',
                    'Oil and Gas Consultancy',
                    'Research, survey and Development Consultancy',
                    'Structural Design',
                    'Transcription',
                    'Translation',
                    'Strategic Planning Consultancy',
                    'Marine Environment Consultancy',
                    'Quality Management Consultancy',
                    'Maritime Management Consultancy',
                    'Proofreading Services',
                    'Careers Development Services',
                    'Personnel Skills Training Services',
                    'Recreational Development Services',
                    'Adult Education Services',
                    'Child Education Services',
                    'Special Needs Education Services',
                    'Vocational Training Services',
                    'Construction Management Services',
                    'Food and Nutrition Services',
                    'Medical Services',
                    'Programme and Project Management Services',
                    'Architectural services',
                    'Forensic and investigation consultancy services',
                    'Health and safety audit services',
                    'Intelligence security and surveillance services',
                    'Land surveying services',
                    'Urban/Town Planning Services',
                    'Civil Engineering Services',
                    'Building Engineering Services',
                    'Mechanical Engineering Services',
                    'Electrical Engineering Services',
                    'Quantity and Building Surveying Services',
                    'Actuarial Services',
                    'Valuation Consultancy Services',
                    'Geoscience Consultancy Services',
                    'Irrigation Engineering Services'
                ]
            }
        ],
        defaultType: 'works'
    },

    // Compliance documents
    complianceDocs: [
        { name: 'BRELA Registration', status: 'approved', uploaded: true },
        { name: 'TIN Certificate', status: 'approved', uploaded: true },
        ],

    // Bid evaluation data
    bidEvaluation: {
        totalBids: 4,
        validSubmissions: 4,
        priceOutliers: 0,
        evaluatorsActive: 3,
        openingReport: {
            openingTime: 'June 12, 2026, 10:00 EAT',
            authorizedBy: ['Mary Komba', 'Joseph Mrema'],
            envelope: 'Technical envelope',
            hashStatus: '4 of 4 verified',
            auditReference: 'AUD-BIDOPEN-2026-014',
            disclosureStatus: 'Financial envelope locked until technical scores are finalized'
        },
        benchmark: {
            buyerEstimate: 4800000000,
            marketMedian: 4860000000,
            regionalAdjustment: 'Dodoma logistics index +2.8%',
            comparableEconomicCost: 4728000000,
            varianceBand: '-2.7% to +1.9%',
            notes: [
                'All bids sit inside the historical healthcare works price band.',
                'No abnormal discounting pattern detected after logistics normalization.',
                'ABC Construction has the strongest delivery feasibility after capacity adjustment.'
            ]
        },
        riskSignals: [
            { supplier: 'ABC Construction Ltd', risk: 'Low', score: 18, driver: 'Strong delivery history and current capacity headroom.' },
            { supplier: 'XYZ Builders', risk: 'Moderate', score: 41, driver: 'Two late milestones in the last 12 months.' },
            { supplier: 'BuildRight Ltd', risk: 'Moderate', score: 37, driver: 'Best technical score, but equipment utilization is near threshold.' },
            { supplier: 'Prime Contractors', risk: 'Low', score: 24, driver: 'Clean compliance record and balanced delivery load.' }
        ],
        collusionSignals: [
            { signal: 'Submission timing', status: 'Clear', detail: 'Bids submitted across a 17-hour spread.' },
            { signal: 'Price spread', status: 'Clear', detail: 'Normalized prices vary by 6.2%.' },
            { signal: 'Document similarity', status: 'Watch', detail: 'Two method statements share a common template, below escalation threshold.' }
        ],
        bids: [
            {
                supplier: 'ABC Construction Ltd',
                technicalScore: 85,
                financialScore: 90,
                totalScore: 87.5,
                integrityHash: '0x1234567890abcdef',
                price: 4800000000
            },
            {
                supplier: 'XYZ Builders',
                technicalScore: 78,
                financialScore: 95,
                totalScore: 84.3,
                integrityHash: '0xabcdef1234567890',
                price: 4950000000
            },
            {
                supplier: 'BuildRight Ltd',
                technicalScore: 92,
                financialScore: 82,
                totalScore: 88.4,
                integrityHash: '0x9876543210fedcba',
                price: 4650000000
            },
            {
                supplier: 'Prime Contractors',
                technicalScore: 88,
                financialScore: 88,
                totalScore: 88.0,
                integrityHash: '0xfedcba0987654321',
                price: 4750000000
            }
        ]
    },

    // Contract negotiation
    contractNegotiation: {
        contractId: 'PX-2026-0892',
        status: 'negotiation',
        poMatched: true,
        budgetVerified: true,
        signaturePending: true,
        messages: [
            { from: 'buyer', message: 'Please review the payment terms in section 3.2', timestamp: '2026-07-02 10:30' },
            { from: 'supplier', message: 'We can accept the revised payment schedule', timestamp: '2026-07-02 11:15' },
            { from: 'buyer', message: 'Great, let\'s proceed with the signature', timestamp: '2026-07-02 14:20' }
        ]
    },

    // Post-award tracking
    postAwardTracking: {
        contractId: 'PX-2026-0892',
        status: 'in_progress',
        progress: 65,
        supplierPerformance: {
            delivery: 85,
            quality: 90,
            communication: 88,
            overall: 87
        },
        supplierHealth: {
            trustScore: 82,
            riskLevel: 'Low',
            lastAudit: '2026-06-30'
        },
        disputes: [
            {
                id: 'D001',
                title: 'Delivery delay for Item #5',
                status: 'resolved',
                priority: 'medium',
                responseDue: 'Closed on August 22, 2026',
                evidence: ['Courier notice', 'Revised delivery schedule', 'Buyer acceptance memo'],
                outcome: 'No penalty; milestone dates updated in contract memory.'
            }
        ],
        invoiceChecks: [
            { invoice: 'INV-2026-001', result: 'Matched', detail: 'PO, GRN, and invoice values align.' },
            { invoice: 'INV-2026-002', result: 'Review', detail: 'GRN accepted after original due date; finance review required.' },
            { invoice: 'INV-2026-003', result: 'Blocked', detail: 'No GRN yet, payment cannot be released.' }
        ]
    },

    // Governance, intelligence, and integration operations
    platformOps: {
        complianceQueue: [
            { alert: 'Shared device fingerprint', severity: 'High', status: 'Investigation open', owner: 'Compliance Officer' },
            { alert: 'Document template similarity', severity: 'Medium', status: 'False-positive review', owner: 'Audit Team' },
            { alert: 'Late invoice anomaly', severity: 'Medium', status: 'Finance escalated', owner: 'Finance Officer' }
        ],
        auditTrail: [
            { time: '2026-06-12 10:00', event: 'Bid opening authorized by two users', ref: 'AUD-BIDOPEN-2026-014' },
            { time: '2026-06-12 10:01', event: 'Four technical envelopes decrypted', ref: 'HASH-SET-9042' },
            { time: '2026-06-24 16:30', event: 'Consensus score report locked', ref: 'EVAL-LOCK-2026-014' },
            { time: '2026-06-30 09:15', event: 'Award routed for approval', ref: 'APP-AWARD-2026-014' }
        ],
        marketIntelligence: {
            liquidityIndex: 74,
            supplierCoverage: '18 eligible suppliers in healthcare works',
            avgBidsPerTender: 4.6,
            priceTrend: '+3.4% quarter over quarter',
            recommendations: [
                'Extend clarification window by 3 days for high-value works.',
                'Invite two Tier 1 suppliers for SME participation balance.',
                'Use Dodoma logistics uplift in financial normalization.'
            ]
        },
        integration: {
            erpName: 'SAP S/4HANA',
            status: 'Healthy',
            lastSync: '2026-05-05 15:20 EAT',
            inbound: ['Budget lines', 'Vendor master', 'Purchase orders'],
            outbound: ['Award decisions', 'Invoice status', 'Supplier scores'],
            discrepancy: '1 unmatched vendor tax ID awaiting review'
        },
        modules: [
            { name: 'Core Procurement', status: 'Active', version: '1.0.0' },
            { name: 'Risk Forecasting', status: 'Active', version: '0.9.4' },
            { name: 'Supplier Financing', status: 'Available', version: '0.4.0' },
            { name: 'Cross-Border Controls', status: 'Available', version: '0.3.1' }
        ]
    },

    // Chart data
    charts: {
        adminActivity: {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
            data: [1200, 1350, 1180, 1420, 1380, 1247]
        },
        buyerSpend: {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
            data: [21000000, 22500000, 21800000, 23500000, 24200000, 25000000]
        }
    },

    // User dashboard operating data. The dashboard filters, sorts, and counts this per active account.
    userWorkspace: {
        urgentItems: [
            { type: 'Pending approvals', count: 3, urgency: 92, due: 'Today', nav: 'award-recommendation', audience: ['buyer', 'all'] },
            { type: 'New bids received', count: 7, urgency: 86, due: '2 hours', nav: 'bid-evaluation', audience: ['buyer', 'all'] },
            { type: 'Contracts awaiting signature', count: 2, urgency: 95, due: 'Today', nav: 'contract-negotiation', audience: ['buyer', 'supplier', 'all'] },
            { type: 'Payments overdue', count: 4, urgency: 89, due: 'Overdue', nav: 'post-award-tracking', audience: ['buyer', 'supplier', 'all'] },
            { type: 'Messages requiring reply', count: 5, urgency: 84, due: '1 day', nav: 'contract-negotiation', audience: ['buyer', 'supplier', 'all'] }
        ],
        workflows: [
            { title: 'Office IT Procurement', status: 'Draft', updatedHours: 2, urgency: 78, nav: 'create-tender', audience: ['buyer', 'all'] },
            { title: 'Vehicle Tender', status: 'Evaluation stage', updatedHours: 5, urgency: 88, nav: 'bid-evaluation', audience: ['buyer', 'all'] },
            { title: 'Contract - ABC Ltd', status: 'Execution', updatedHours: 1, urgency: 91, nav: 'post-award-tracking', audience: ['buyer', 'supplier', 'all'] },
            { title: 'Medical Equipment Bid', status: 'Clarification response due', updatedHours: 3, urgency: 87, nav: 'bidding-workspace', audience: ['supplier', 'all'] }
        ],
        quickActions: [
            { title: 'Review approvals', detail: 'Award and budget approvals waiting', nav: 'award-recommendation', audience: ['buyer', 'all'], signal: 'approvals' },
            { title: 'Evaluate new bids', detail: 'Open technical and financial review', nav: 'bid-evaluation', audience: ['buyer', 'all'], signal: 'bids' },
            { title: 'Sign contract', detail: 'Complete digital signature workflow', nav: 'contract-negotiation', audience: ['buyer', 'supplier', 'all'], signal: 'contracts' },
            { title: 'Reply to messages', detail: 'Procurement and contract conversations', nav: 'contract-negotiation', audience: ['buyer', 'supplier', 'all'], signal: 'messages' },
            { title: 'Find opportunities', detail: 'Open matching tenders and tenders near close', nav: 'supplier-marketplace', audience: ['supplier', 'all'], signal: 'opportunities' },
            { title: 'Create tender', detail: 'Start a new buyer procurement', nav: 'create-tender', audience: ['buyer', 'all'], signal: 'drafts' }
        ],
        appShortcuts: [
            { app: 'Procurement', detail: 'Marketplace, create tender, bid', usage: 96, nav: 'supplier-marketplace', audience: ['buyer', 'supplier', 'all'] },
            { app: 'Evaluation', detail: 'Bid opening, scoring, review', usage: 94, nav: 'bid-evaluation', audience: ['buyer', 'all'] },
            { app: 'Awarding and Contract', detail: 'Awards, approvals, signatures', usage: 92, nav: 'award-recommendation', audience: ['buyer', 'supplier', 'all'] },
            { app: 'Records & History', detail: 'Past tenders, bids, awards, cancellations', usage: 90, nav: 'records-history', audience: ['buyer', 'supplier', 'all'] },
            { app: 'IAM', detail: 'Registration and eKYC review', usage: 88, nav: 'verification-status', audience: ['buyer', 'supplier', 'all'] },
            { app: 'Dashboard', detail: 'Your work, spend, and insights', usage: 84, nav: 'workspace-dashboard', audience: ['buyer', 'supplier', 'all'] }
        ],
        insights: [
            { type: 'Suggested supplier', title: '3 suppliers match Office IT Procurement', detail: 'Two have low risk and recent delivery capacity.', urgency: 78, nav: 'supplier-marketplace', audience: ['buyer', 'all'] },
            { type: 'Price insight', title: 'Network equipment prices up 4.2%', detail: 'Use the updated benchmark before publishing.', urgency: 72, nav: 'create-tender', audience: ['buyer', 'all'] },
            { type: 'Risk alert', title: 'One evaluator conflict needs review', detail: 'Resolve before award recommendation is locked.', urgency: 90, nav: 'award-recommendation', audience: ['buyer', 'all'] },
            { type: 'Matching tender', title: 'New ICT tender matches your profile', detail: 'Closes soon and accepts digital service providers.', urgency: 84, nav: 'supplier-marketplace', audience: ['supplier', 'all'] },
            { type: 'Partnership', title: 'Logistics partner available in Dodoma', detail: 'Could improve bid feasibility for rural delivery.', urgency: 70, nav: 'supplier-marketplace', audience: ['supplier', 'all'] },
            { type: 'Market trend', title: 'Healthcare works liquidity is improving', detail: 'Average eligible supplier count rose this month.', urgency: 64, nav: 'workspace-dashboard', audience: ['buyer', 'supplier', 'all'] }
        ]
    }
};

// Export for use in other modules
window.mockData = mockData;
